(iac.cc.results
Projects
p0
(dp1
S'job_name'
p2
S'test'
p3
sS'projects'
p4
(lp5
(iac.cc.results
Project
p6
(dp7
S'branches'
p8
(dp9
sS'name'
p10
S'VICON-ROS'
p11
sS'trace'
p12
S''
p13
sS'testing_error'
p14
g13
sS'catkin_packages'
p15
(lp16
(iac.cc.results
Catkin_package
p17
(dp18
S'doxygen'
p19
Nsg10
S'xenomai_ros'
p20
sS'unit_tests'
p21
(lp22
sS'demos'
p23
(lp24
sS'id'
p25
S'catkin_package_38167256'
p26
sS'unit_tests_errors'
p27
Nsba(iac.cc.results
Catkin_package
p28
(dp29
g19
Nsg10
S'catkin'
p30
sg21
(lp31
(iac.cc.results
Unit_tests
p32
(dp33
S'nb_failures'
p34
I0
sS'error'
p35
Nsg10
S'nosetests-test.unit_tests.xml'
p36
sS'nb_tests'
p37
I39
sS'testsuits'
p38
(dp39
S'nosetests'
p40
(iac.cc.results
TestSuit
p41
(dp42
g34
I0
sS'testcases'
p43
(dp44
S'test_download'
p45
(iac.cc.results
TestCase
p46
(dp47
S'failure'
p48
Nsg10
g45
sS'time'
p49
F0.016
sbsS'test_prefix_env'
p50
(iac.cc.results
TestCase
p51
(dp52
g48
Nsg10
g50
sg49
F0.0
sbsS'test_parse_args_folders'
p53
(iac.cc.results
TestCase
p54
(dp55
g48
Nsg10
g53
sg49
F0.002
sbsS'test_replace_version'
p56
(iac.cc.results
TestCase
p57
(dp58
g48
Nsg10
g56
sg49
F0.0
sbsS'test_read_junit'
p59
(iac.cc.results
TestCase
p60
(dp61
g48
Nsg10
g59
sg49
F0.001
sbsS'test_generate_cmake_file_msg_srv'
p62
(iac.cc.results
TestCase
p63
(dp64
g48
Nsg10
g62
sg49
F0.0
sbsS'test_get_source_paths'
p65
(iac.cc.results
TestCase
p66
(dp67
g48
Nsg10
g65
sg49
F0.001
sbsS'test_generate_cmake_file_noallprefix'
p68
(iac.cc.results
TestCase
p69
(dp70
g48
Nsg10
g68
sg49
F0.0
sbsS'test_run_command_unicode'
p71
(iac.cc.results
TestCase
p72
(dp73
g48
Nsg10
g71
sg49
F0.0
sbsS'test_generate_cmake_file'
p74
(iac.cc.results
TestCase
p75
(dp76
g48
Nsg10
g74
sg49
F0.0
sbsS'test_symlink_or_copy'
p77
(iac.cc.results
TestCase
p78
(dp79
g48
Nsg10
g77
sg49
F0.001
sbsS'test_remove_from_env'
p80
(iac.cc.results
TestCase
p81
(dp82
g48
Nsg10
g80
sg49
F0.001
sbsS'test_interrogate_setup_py'
p83
(iac.cc.results
TestCase
p84
(dp85
g48
Nsg10
g83
sg49
F0.0
sbsS'test_parse_args_first'
p86
(iac.cc.results
TestCase
p87
(dp88
g48
Nsg10
g86
sg49
F0.001
sbsS'test_init_workspace'
p89
(iac.cc.results
TestCase
p90
(dp91
g48
Nsg10
g89
sg49
F0.001
sbsS'test_checkmd5'
p92
(iac.cc.results
TestCase
p93
(dp94
g48
Nsg10
g92
sg49
F0.001
sbsS'test_main'
p95
(iac.cc.results
TestCase
p96
(dp97
g48
Nsg10
S'test_main'
p98
sg49
F0.03
sbsS'test_terminal_colors'
p99
(iac.cc.results
TestCase
p100
(dp101
g48
Nsg10
g99
sg49
F0.0
sbsS'test_symlinked_src'
p102
(iac.cc.results
TestCase
p103
(dp104
g48
Nsg10
g102
sg49
F0.086
sbsS'test_print_summary'
p105
(iac.cc.results
TestCase
p106
(dp107
g48
Nsg10
g105
sg49
F0.0
sbsS'test_env_cached_static'
p108
(iac.cc.results
TestCase
p109
(dp110
g48
Nsg10
g108
sg49
F0.005
sbsS'test_get_reversed_workspaces'
p111
(iac.cc.results
TestCase
p112
(dp113
g48
Nsg10
g111
sg49
F0.001
sbsS'test_tiny_xml'
p114
(iac.cc.results
TestCase
p115
(dp116
g48
Nsg10
g114
sg49
F0.001
sbsS'test_update_versions'
p117
(iac.cc.results
TestCase
p118
(dp119
g48
Nsg10
g117
sg49
F0.003
sbsS'test_extract_cmake_and_make_arguments'
p120
(iac.cc.results
TestCase
p121
(dp122
g48
Nsg10
g120
sg49
F0.0
sbsS'test_test_results'
p123
(iac.cc.results
TestCase
p124
(dp125
g48
Nsg10
g123
sg49
F0.001
sbsS'test_generate_cmake_file_invalid'
p126
(iac.cc.results
TestCase
p127
(dp128
g48
Nsg10
g126
sg49
F0.0
sbsS'test_get_locations'
p129
(iac.cc.results
TestCase
p130
(dp131
g48
Nsg10
g129
sg49
F0.0
sbsS'test_parse_args_empty'
p132
(iac.cc.results
TestCase
p133
(dp134
g48
Nsg10
g132
sg49
F0.001
sbsS'runTest'
p135
(iac.cc.results
TestCase
p136
(dp137
g48
Nsg10
S'runTest'
p138
sg49
F0.0
sbsS'test_get_workspaces'
p139
(iac.cc.results
TestCase
p140
(dp141
g48
Nsg10
g139
sg49
F0.001
sbsS'test_handle_cmake_args'
p142
(iac.cc.results
TestCase
p143
(dp144
g48
Nsg10
g142
sg49
F0.004
sbsS'test_extract_jobs_flags'
p145
(iac.cc.results
TestCase
p146
(dp147
g48
Nsg10
g145
sg49
F0.001
sbsS'test_empty_workspace'
p148
(iac.cc.results
TestCase
p149
(dp150
g48
Nsg10
g148
sg49
F0.003
sbsS'test_safe_xml_regex'
p151
(iac.cc.results
TestCase
p152
(dp153
g48
Nsg10
g151
sg49
F0.0
sbssg10
g40
sg37
I39
sbssba(iac.cc.results
Unit_tests
p154
(dp155
g34
I0
sg35
Nsg10
S'nosetests-test.local_tests.xml'
p156
sg37
I4
sg38
(dp157
S'nosetests'
p158
(iac.cc.results
TestSuit
p159
(dp160
g34
I0
sg43
(dp161
S'test_env_cached_static'
p162
(iac.cc.results
TestCase
p163
(dp164
g48
Nsg10
g162
sg49
F0.142
sbsS'test_noproject'
p165
(iac.cc.results
TestCase
p166
(dp167
g48
Nsg10
g165
sg49
F5.218
sbsS'test_nolang'
p168
(iac.cc.results
TestCase
p169
(dp170
g48
Nsg10
g168
sg49
F3.357
sbsS'test_catkin_only'
p171
(iac.cc.results
TestCase
p172
(dp173
g48
Nsg10
g171
sg49
F2.841
sbssg10
g158
sg37
I4
sbssbasg23
(lp174
sg25
S'catkin_package_38739192'
p175
sg27
Nsba(iac.cc.results
Catkin_package
p176
(dp177
g19
Nsg10
S'ros_realtime'
p178
sg21
(lp179
sg23
(lp180
sg25
S'catkin_package_38699088'
p181
sg27
Nsba(iac.cc.results
Catkin_package
p182
(dp183
g19
Nsg10
S'vicon_subscriber'
p184
sg21
(lp185
sg23
(lp186
(iac.cc.results
Demo
p187
(dp188
g10
S'running_vicon_object_demo'
p189
sS'success'
p190
I01
sS'out'
p191
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/setup.bash\ncd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/src/catkin/perception/vicon_subscriber/demos/\nchmod +x running_vicon_object_demo\n./running_vicon_object_demo /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel\n\n\n------ DEMO START ------\n./running_vicon_object_demo: line 17: ./vicon_object_sh: No such file or directory\n------ DEMO END ------\n... logging to /Network/Servers/bleyl/Volumes/bleyl/vberenz/.ros/log/166feef2-088f-11e6-813b-b8ca3aad4e6c/roslaunch-bleyl-29547.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is <1GB.\n\x1b]2;roscore\x07\n\x1b[1mstarted roslaunch server http://bleyl:45547/\x1b[0m\nros_comm version 1.9.55\n\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n\nauto-starting new master\n\x1b[1mprocess[master]: started with pid [29562]\x1b[0m\n\x1b[1mROS_MASTER_URI=http://bleyl:11311/\x1b[0m\n\x1b]2;roscore http://bleyl:11311/\x07\n\x1b[1msetting /run_id to 166feef2-088f-11e6-813b-b8ca3aad4e6c\x1b[0m\n\x1b[1mprocess[rosout-1]: started with pid [29575]\x1b[0m\nstarted core service [/rosout]\n[rosout-1] killing on exit\n[master] killing on exit\nshutting down processing monitor...\n... shutting down processing monitor complete\n\x1b[1mdone\x1b[0m\n'
p192
sbasg25
S'catkin_package_38688600'
p193
sg27
Nsba(iac.cc.results
Catkin_package
p194
(dp195
g19
Nsg10
S'vicon_bridge'
p196
sg21
(lp197
sg23
(lp198
sg25
S'catkin_package_38774184'
p199
sg27
Nsba(iac.cc.results
Catkin_package
p200
(dp201
g19
Nsg10
S'lockfree'
p202
sg21
(lp203
(iac.cc.results
Unit_tests
p204
(dp205
g34
I0
sg35
Nsg10
S'gtest-test_object_pool.xml'
p206
sg37
I2
sg38
(dp207
S'ObjectPool'
p208
(iac.cc.results
TestSuit
p209
(dp210
g34
I0
sg43
(dp211
S'oneElement'
p212
(iac.cc.results
TestCase
p213
(dp214
g48
Nsg10
g212
sg49
F0.0
sbsS'multipleElements'
p215
(iac.cc.results
TestCase
p216
(dp217
g48
Nsg10
g215
sg49
F0.0
sbssg10
g208
sg37
I2
sbssba(iac.cc.results
Unit_tests
p218
(dp219
g34
I0
sg35
Nsg10
S'gtest-test_freelist.xml'
p220
sg37
I4
sg38
(dp221
S'FreeList'
p222
(iac.cc.results
TestSuit
p223
(dp224
g34
I0
sg43
(dp225
S'multipleThreads'
p226
(iac.cc.results
TestCase
p227
(dp228
g48
Nsg10
g226
sg49
F10.006
sbsS'hasOutstandingAllocations'
p229
(iac.cc.results
TestCase
p230
(dp231
g48
Nsg10
g229
sg49
F0.0
sbsS'oneElement'
p232
(iac.cc.results
TestCase
p233
(dp234
g48
Nsg10
g232
sg49
F0.0
sbsS'multipleElements'
p235
(iac.cc.results
TestCase
p236
(dp237
g48
Nsg10
g235
sg49
F0.0
sbssg10
g222
sg37
I4
sbssbasg23
(lp238
sg25
S'catkin_package_38754352'
p239
sg27
Nsba(iac.cc.results
Catkin_package
p240
(dp241
g19
Nsg10
S'rosatomic'
p242
sg21
(lp243
(iac.cc.results
Unit_tests
p244
(dp245
g34
I0
sg35
Nsg10
S'gtest-utest.xml'
p246
sg37
I1
sg38
(dp247
S'Atomic'
p248
(iac.cc.results
TestSuit
p249
(dp250
g34
I0
sg43
(dp251
S'all'
p252
(iac.cc.results
TestCase
p253
(dp254
g48
Nsg10
g252
sg49
F0.0
sbssg10
g248
sg37
I1
sbssbasg23
(lp255
sg25
S'catkin_package_37848632'
p256
sg27
Nsba(iac.cc.results
Catkin_package
p257
(dp258
g19
Nsg10
S'rt_timer'
p259
sg21
(lp260
sg23
(lp261
sg25
S'catkin_package_38703400'
p262
sg27
Nsba(iac.cc.results
Catkin_package
p263
(dp264
g19
Nsg10
S'ros_rt_test'
p265
sg21
(lp266
sg23
(lp267
sg25
S'catkin_package_38753560'
p268
sg27
Nsba(iac.cc.results
Catkin_package
p269
(dp270
g19
Nsg10
S'allocators'
p271
sg21
(lp272
(iac.cc.results
Unit_tests
p273
(dp274
g34
I0
sg35
Nsg10
S'gtest-test_aligned_alloc.xml'
p275
sg37
I2
sg38
(dp276
S'AlignedAlloc'
p277
(iac.cc.results
TestSuit
p278
(dp279
g34
I0
sg43
(dp280
S'mallocfree'
p281
(iac.cc.results
TestCase
p282
(dp283
g48
Nsg10
g281
sg49
F0.008
sbsS'stlAllocator'
p284
(iac.cc.results
TestCase
p285
(dp286
g48
Nsg10
g284
sg49
F6.957
sbssg10
g277
sg37
I2
sbssbasg23
(lp287
sg25
S'catkin_package_38674728'
p288
sg27
Nsba(iac.cc.results
Catkin_package
p289
(dp290
g19
Nsg10
S'rosrt'
p291
sg21
(lp292
sg23
(lp293
sg25
S'catkin_package_38666184'
p294
sg27
NsbasS'build_message'
p295
S'COMMAND:catkin_make -j install\n------------------------------\n-- The C compiler identification is GNU\n-- The CXX compiler identification is GNU\n-- Check for working C compiler: /usr/bin/gcc\n-- Check for working C compiler: /usr/bin/gcc -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Check for working CXX compiler: /usr/bin/c++\n-- Check for working CXX compiler: /usr/bin/c++ -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Using CATKIN_DEVEL_PREFIX: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel\n-- Using CMAKE_PREFIX_PATH: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/workspace/devel;/opt/ros/groovy\n-- This workspace overlays: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/workspace/devel;/opt/ros/groovy\n-- Found PythonInterp: /usr/bin/python (found version "2.7.3")\n-- Using PYTHON_EXECUTABLE: /usr/bin/python\n-- Python version: 2.7\n-- Using Debian Python package layout\n-- Using CATKIN_ENABLE_TESTING: ON\n-- Call enable_testing()\n-- Using CATKIN_TEST_RESULTS_DIR: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/test_results\n-- Looking for include files CMAKE_HAVE_PTHREAD_H\n-- Looking for include files CMAKE_HAVE_PTHREAD_H - found\n-- Looking for pthread_create in pthreads\n-- Looking for pthread_create in pthreads - not found\n-- Looking for pthread_create in pthread\n-- Looking for pthread_create in pthread - found\n-- Found Threads: TRUE \n-- Found gtest sources under \'/usr/src/gtest\': gtests will be built\n-- catkin 0.5.90\n-- BUILD_SHARED_LIBS is on\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- ~~  traversing 10 packages in topological order:\n-- ~~  - ros_realtime (metapackage)\n-- ~~  - allocators\n-- ~~  - rosatomic\n-- ~~  - lockfree\n-- ~~  - rt_timer\n-- ~~  - xenomai_ros\n-- ~~  - rosrt\n-- ~~  - ros_rt_test\n-- ~~  - vicon_bridge\n-- ~~  - vicon_subscriber\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- +++ processing catkin metapackage: \'ros_realtime\'\n-- ==> add_subdirectory(catkin/ros/ros_realtime/ros_realtime)\n-- +++ processing catkin package: \'allocators\'\n-- ==> add_subdirectory(catkin/ros/ros_realtime/allocators)\n-- Boost version: 1.46.1\n-- +++ processing catkin package: \'rosatomic\'\n-- ==> add_subdirectory(catkin/ros/ros_realtime/rosatomic)\n-- +++ processing catkin package: \'lockfree\'\n-- ==> add_subdirectory(catkin/ros/ros_realtime/lockfree)\n-- +++ processing catkin package: \'rt_timer\'\n-- ==> add_subdirectory(catkin/ros/ros_realtime/rt_timer)\n-- +++ processing catkin package: \'xenomai_ros\'\n-- ==> add_subdirectory(catkin/ros/xenomai-ros)\n-- +++ processing catkin package: \'rosrt\'\n-- ==> add_subdirectory(catkin/ros/ros_realtime/rosrt)\n-- xenomai NOT found. (/usr/local;/usr)\n-- Could NOT find Xenomai (missing:  Xenomai_ROOT_DIR Xenomai_LIBRARY_NATIVE Xenomai_LIBRARY_XENOMAI Xenomai_LIBRARY_PTHREAD_RT Xenomai_LIBRARY_RTDM Xenomai_VERSION Xenomai_LIBRARY_RTDK) \n-- Boost version: 1.46.1\n-- Found the following Boost libraries:\n--   thread\n-- +++ processing catkin package: \'ros_rt_test\'\n-- ==> add_subdirectory(catkin/ros/ros_rt_basic_example)\n-- xenomai NOT found. (/usr/local;/usr)\n-- Could NOT find Xenomai (missing:  Xenomai_ROOT_DIR Xenomai_LIBRARY_NATIVE Xenomai_LIBRARY_XENOMAI Xenomai_LIBRARY_PTHREAD_RT Xenomai_LIBRARY_RTDM Xenomai_VERSION Xenomai_LIBRARY_RTDK) \n-- +++ processing catkin package: \'vicon_bridge\'\n-- ==> add_subdirectory(catkin/perception/vicon_bridge)\n-- Using these message generators: gencpp;genlisp;genpy\n-- vicon_bridge: 3 messages, 2 services\n-- +++ processing catkin package: \'vicon_subscriber\'\n-- ==> add_subdirectory(catkin/perception/vicon_subscriber)\n-- Configuring done\n-- Generating done\n-- Build files have been written to: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build\nScanning dependencies of target geometry_msgs_generate_messages_lisp\nScanning dependencies of target geometry_msgs_generate_messages_py\nScanning dependencies of target testclient\nScanning dependencies of target vicon_bridge_gencfg\nScanning dependencies of target geometry_msgs_generate_messages_cpp\nScanning dependencies of target msvc_bridge\nScanning dependencies of target lockfree\n[  0%] [  0%] Built target geometry_msgs_generate_messages_lisp\n[  2%] [  2%] Built target geometry_msgs_generate_messages_cpp\nBuilt target geometry_msgs_generate_messages_py\n[  5%] [  8%] Building CXX object catkin/perception/vicon_bridge/CMakeFiles/testclient.dir/src/ViconDataStreamSDK_CPPTest.cpp.o\n[ 11%] Building CXX object catkin/perception/vicon_bridge/CMakeFiles/msvc_bridge.dir/src/msvc_bridge.cpp.o\nScanning dependencies of target vicon_bridge_generate_messages_lisp\nScanning dependencies of target vicon_bridge_generate_messages_py\nScanning dependencies of target vicon_bridge_generate_messages_cpp\nGenerating dynamic reconfigure files from cfg/tf_distort.cfg: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/include/vicon_bridge/tf_distortConfig.h /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/cfg/tf_distortConfig.py\nBuilding CXX object catkin/ros/ros_realtime/lockfree/CMakeFiles/lockfree.dir/src/free_list.cpp.o\n[ 14%] [ 17%] [ 20%] [ 23%] [ 26%] [ 29%] [ 32%] [ 35%] [ 38%] [ 41%] [ 44%] [ 47%] [ 50%] Generating Lisp code from vicon_bridge/Marker.msg\nGenerating Lisp code from vicon_bridge/TfDistortInfo.msg\n[ 52%] [ 55%] Scanning dependencies of target vicon_subscriber\nGenerating C++ code from vicon_bridge/Markers.msg\nGenerating Python from MSG vicon_bridge/Marker\nGenerating Lisp code from vicon_bridge/Markers.msg\nGenerating C++ code from vicon_bridge/Marker.msg\nGenerating C++ code from vicon_bridge/TfDistortInfo.msg\nGenerating Python from MSG vicon_bridge/Markers\nGenerating C++ code from vicon_bridge/viconCalibrateSegment.srv\nGenerating Lisp code from vicon_bridge/viconCalibrateSegment.srv\nGenerating Python from MSG vicon_bridge/TfDistortInfo\nGenerating Lisp code from vicon_bridge/viconGrabPose.srv\nGenerating C++ code from vicon_bridge/viconGrabPose.srv\nGenerating Python code from SRV vicon_bridge/viconGrabPose\nGenerating Python code from SRV vicon_bridge/viconCalibrateSegment\n[ 58%] Building CXX object catkin/perception/vicon_subscriber/CMakeFiles/vicon_subscriber.dir/src/vicon_object.cpp.o\n[ 61%] [ 64%] [ 64%] Generating Python msg __init__.py for vicon_bridge\nGenerating Python srv __init__.py for vicon_bridge\nBuilt target vicon_bridge_generate_messages_lisp\nLinking CXX shared library /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/libmsvc_bridge.so\n[ 64%] Built target vicon_bridge_generate_messages_py\n[ 64%] Built target msvc_bridge\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/vicon_bridge/testclient\n[ 64%] Built target vicon_bridge_generate_messages_cpp\nScanning dependencies of target vicon_bridge_gencpp\nScanning dependencies of target vicon_bridge_generate_messages\n[ 64%] Built target vicon_bridge_gencpp\n[ 64%] Built target vicon_bridge_generate_messages\nScanning dependencies of target calibrate\n[ 67%] Scanning dependencies of target vicon_bridge\n[ 67%] Built target testclient\nBuilding CXX object catkin/perception/vicon_bridge/CMakeFiles/calibrate.dir/src/calibrate_segment.cpp.o\n[ 70%] Building CXX object catkin/perception/vicon_bridge/CMakeFiles/vicon_bridge.dir/src/vicon_bridge.cpp.o\nGenerating reconfiguration files for tf_distort in vicon_bridge\nWrote header file in /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/include/vicon_bridge/tf_distortConfig.h\n[ 70%] Built target vicon_bridge_gencfg\nScanning dependencies of target tf_distort\n[ 73%] Building CXX object catkin/perception/vicon_bridge/CMakeFiles/tf_distort.dir/src/tf_distort.cpp.o\nLinking CXX shared library /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/liblockfree.so\n[ 73%] Built target lockfree\nScanning dependencies of target rosrt\n[ 76%] [ 82%] [ 88%] [ 88%] [ 88%] Building CXX object catkin/ros/ros_realtime/rosrt/CMakeFiles/rosrt.dir/src/init.cpp.o\nBuilding CXX object catkin/ros/ros_realtime/rosrt/CMakeFiles/rosrt.dir/src/publisher.cpp.o\nBuilding CXX object catkin/ros/ros_realtime/rosrt/CMakeFiles/rosrt.dir/src/malloc.cpp.o\nBuilding CXX object catkin/ros/ros_realtime/rosrt/CMakeFiles/rosrt.dir/src/simple_gc.cpp.o\nBuilding CXX object catkin/ros/ros_realtime/rosrt/CMakeFiles/rosrt.dir/src/subscriber.cpp.o\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/vicon_bridge/calibrate\n[ 88%] Built target calibrate\nLinking CXX shared library /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/librosrt.so\n[ 88%] Built target rosrt\nScanning dependencies of target ros_rt_test_subscriber\nScanning dependencies of target ros_rt_test_publisher\n[ 91%] [ 94%] Building CXX object catkin/ros/ros_rt_basic_example/CMakeFiles/ros_rt_test_subscriber.dir/src/ros_rt_test_subscriber.cpp.o\nBuilding CXX object catkin/ros/ros_rt_basic_example/CMakeFiles/ros_rt_test_publisher.dir/src/ros_rt_test_publisher.cpp.o\nLinking CXX shared library /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/libvicon_subscriber.so\n[ 94%] Built target vicon_subscriber\nScanning dependencies of target vicon_object_sh\nScanning dependencies of target vicon_subscriber_console\n[ 97%] [100%] Building CXX object catkin/perception/vicon_subscriber/CMakeFiles/vicon_object_sh.dir/src/vicon_object_sh.cpp.o\nBuilding CXX object catkin/perception/vicon_subscriber/CMakeFiles/vicon_subscriber_console.dir/src/vicon_subscriber_console.cpp.o\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/ros_rt_test/ros_rt_test_publisher\n[100%] Built target ros_rt_test_publisher\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/ros_rt_test/ros_rt_test_subscriber\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/vicon_bridge/tf_distort\n[100%] Built target ros_rt_test_subscriber\n[100%] Built target tf_distort\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/vicon_bridge/vicon_bridge\n[100%] Built target vicon_bridge\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/vicon_subscriber/vicon_object_sh\n[100%] Built target vicon_object_sh\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/vicon_subscriber/vicon_subscriber_console\n[100%] Built target vicon_subscriber_console\nInstall the project...\n-- Install configuration: ""\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/_setup_util.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/env.sh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/setup.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/setup.sh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/setup.zsh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/.rosinstall\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/etc/catkin/profile.d/05.catkin_make.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/etc/catkin/profile.d/05.catkin_make_isolated.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/catkin.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkinConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkinConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/LICENSE\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/eigen/cmake/eigen-config.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/eigen/cmake/eigen-config-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/toplevel.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/assert.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/em\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/em/pkg.pc.em\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/em/order_packages.cmake.em\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_install_python.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_package_xml.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_generate_environment.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/list_insert_in_workspace_order.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/setup.bash.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/__init__.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/setup.zsh.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/python_distutils_install.sh.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/generate_cached_setup.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/pkgConfig.cmake.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/_setup_util.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/script.sh.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/Doxyfile.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/setup.sh.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/env-hook.context.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/env.bat.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/safe_execute_install.cmake.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/env.sh.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/order_packages.context.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/setup.bat.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/script.bash.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/python_distutils_install.bat.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/relay.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/script.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/script.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/_setup_util.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/pkgConfig-version.cmake.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/pkg.context.pc.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/rosinstall.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/templates/cfg-extras.context.py.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/tools\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/tools/libraries.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/tools/bz2.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/tools/doxygen.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/tools/threads.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/tools/rt.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/interrogate_setup_dot_py.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test/nosetests.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test/tests.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test/download_checkmd5.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test/catkin_download_test_data.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test/run_tests.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test/download_test_data.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/test/gtest.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/parse_arguments.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_libraries.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/shell.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/list_append_deduplicate.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/string_starts_with.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_package.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/order_paths.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/stamp.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/find_program_required.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_metapackage.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/platform\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/platform/lsb.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/platform/ubuntu.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/platform/windows.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_add_env_hooks.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/atomic_configure_file.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_destinations.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/debug_message.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/em_expand.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/list_append_unique.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/python.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/parse_package_xml.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/all.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/empy.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_workspace.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/safe_execute_process.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/catkin_python_setup.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/env-hooks\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/env-hooks/05.catkin_make.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/env-hooks/05.catkin_make_isolated.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/env-hooks/05.catkin-test-results.bat.develspace.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/env-hooks/05.catkin-test-results.sh.develspace.in\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/catkin/cmake/legacy.cmake\n+ [ -n  ]\n+ cd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/src/catkin/third_party/catkin\n+ /usr/bin/env PYTHONPATH=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/lib/python2.7/dist-packages:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/workspace/devel/lib/python2.7/dist-packages:/opt/ros/groovy/lib/python2.7/dist-packages:/opt/ros/groovy/bin:/Network/Servers/bleyl/Volumes/bleyl/vberenz/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/amd-clmc/scripts:/Network/Servers/bleyl/Volumes/bleyl/vberenz/.local/bin:/Network/Servers/bleyl/Volumes/bleyl/vberenz/bin/:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Libraries/aldebaran/pynaoqi-python2.7-2.1.2.17-linux64 CATKIN_BINARY_DIR=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build /usr/bin/python /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/src/catkin/third_party/catkin/setup.py build --build-base /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin install --install-layout=deb --prefix=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install --install-scripts=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\nrunning build\nrunning build_py\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/environment_cache.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/terminal_color.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/tidy_xml.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/workspace_vcs.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/test_results.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/builder.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/package_version.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/init_workspace.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/cmake.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/workspace.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/find_in_workspaces.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\ncopying python/catkin/__init__.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin\nrunning build_scripts\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_find -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_init_workspace -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_make -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_make_isolated -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_package_version -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_prepare_release -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_test_results -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\ncopying and adjusting bin/catkin_topological_order -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_find from 644 to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_init_workspace from 644 to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_make from 644 to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_make_isolated from 644 to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_package_version from 644 to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_prepare_release from 644 to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_test_results from 644 to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_topological_order from 644 to 755\nrunning install\nrunning install_lib\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/environment_cache.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/terminal_color.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/tidy_xml.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/workspace_vcs.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/test_results.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/builder.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/package_version.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/init_workspace.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/cmake.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/workspace.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/find_in_workspaces.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/lib.linux-x86_64-2.7/catkin/__init__.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/environment_cache.py to environment_cache.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/terminal_color.py to terminal_color.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/tidy_xml.py to tidy_xml.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/workspace_vcs.py to workspace_vcs.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/test_results.py to test_results.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/builder.py to builder.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/package_version.py to package_version.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/init_workspace.py to init_workspace.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/cmake.py to cmake.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/workspace.py to workspace.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/find_in_workspaces.py to find_in_workspaces.pyc\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin/__init__.py to __init__.pyc\nrunning install_scripts\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_init_workspace -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_prepare_release -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_make_isolated -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_package_version -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_find -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_topological_order -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_make -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build/catkin/third_party/catkin/scripts-2.7/catkin_test_results -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_init_workspace to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_prepare_release to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_make_isolated to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_package_version to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_find to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_topological_order to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_make to 755\nchanging mode of /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/bin/catkin_test_results to 755\nrunning install_egg_info\nWriting /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/catkin-0.5.90.egg-info\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/ros_realtime/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/allocators.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/allocators/cmake/allocatorsConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/allocators/cmake/allocatorsConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/allocators/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/rosatomic.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rosatomic/cmake/rosatomicConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rosatomic/cmake/rosatomicConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rosatomic/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/lockfree.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/lockfree/cmake/lockfreeConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/lockfree/cmake/lockfreeConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/lockfree/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/rt_timer.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rt_timer/cmake/rt_timerConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rt_timer/cmake/rt_timerConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rt_timer/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/xenomai_ros.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/xenomai_ros/cmake/xenomai_ros-extras.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/xenomai_ros/cmake/xenomai_rosConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/xenomai_ros/cmake/xenomai_rosConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/xenomai_ros/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/xenomai_ros/cmake/XenomaiConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/rosrt.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rosrt/cmake/rosrt-extras.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rosrt/cmake/rosrtConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rosrt/cmake/rosrtConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/rosrt/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/ros_rt_test.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/ros_rt_test/cmake/ros_rt_testConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/ros_rt_test/cmake/ros_rt_testConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/ros_rt_test/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/msg/Marker.msg\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/msg/Markers.msg\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/msg/TfDistortInfo.msg\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/srv/viconCalibrateSegment.srv\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/srv/viconGrabPose.srv\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/cmake/vicon_bridge-msg-paths.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/viconCalibrateSegment.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/viconCalibrateSegmentRequest.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/viconGrabPoseResponse.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/viconCalibrateSegmentResponse.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/viconGrabPose.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/Marker.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/Markers.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/TfDistortInfo.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/viconGrabPoseRequest.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/tf_distortConfig.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/_package_TfDistortInfo.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/_package_Markers.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/Markers.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/_package.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/Marker.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/vicon_bridge-msg.asd\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/_package_Marker.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/msg/TfDistortInfo.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/srv\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/srv/_package_viconCalibrateSegment.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/srv/vicon_bridge-srv.asd\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/srv/_package_viconGrabPose.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/srv/_package.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/srv/viconCalibrateSegment.lisp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/common-lisp/ros/vicon_bridge/srv/viconGrabPose.lisp\nListing /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/__init__.py ...\nListing /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/cfg ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/cfg/__init__.py ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/cfg/tf_distortConfig.py ...\nListing /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/msg ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/msg/_Marker.py ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/msg/_Markers.py ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/msg/_TfDistortInfo.py ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/msg/__init__.py ...\nListing /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/srv ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/srv/__init__.py ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/srv/_viconCalibrateSegment.py ...\nCompiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/srv/_viconGrabPose.py ...\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/__init__.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/tf_distortConfig.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/tf_distortConfig.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/__init__.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/__init__.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/__init__.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/_Marker.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/_Markers.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/_Markers.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/__init__.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/_TfDistortInfo.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/_TfDistortInfo.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/msg/_Marker.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/srv\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/srv/__init__.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/srv/_viconCalibrateSegment.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/srv/_viconGrabPose.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/srv/_viconCalibrateSegment.pyc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/srv/_viconGrabPose.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/srv/__init__.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/__init__.py\n-- Up-to-date: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/include/vicon_bridge/tf_distortConfig.h\n-- Up-to-date: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/__init__.py\nListing /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib/python2.7/dist-packages/vicon_bridge/cfg ...\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg\n-- Up-to-date: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/__init__.pyc\n-- Up-to-date: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/tf_distortConfig.pyc\n-- Up-to-date: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/tf_distortConfig.py\n-- Up-to-date: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/python2.7/dist-packages/vicon_bridge/cfg/__init__.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/vicon_bridge.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/cmake/vicon_bridge-msg-extras.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/cmake/vicon_bridgeConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/cmake/vicon_bridgeConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_bridge/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/pkgconfig/vicon_subscriber.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_subscriber/cmake/vicon_subscriberConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_subscriber/cmake/vicon_subscriberConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/share/vicon_subscriber/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/libvicon_subscriber.so\n-- Set runtime path of "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib/libvicon_subscriber.so" to "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib:/opt/ros/groovy/lib"\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/demos/vicon_object_sh\n-- Set runtime path of "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/demos/vicon_object_sh" to "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/lib:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel/lib:/opt/ros/groovy/lib"\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install/demos/running_vicon_object_demo\nBase path: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace\nSource space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/src\nBuild space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build\nDevel space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel\nInstall space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install\nCreating symlink "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/src/CMakeLists.txt" pointing to "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/workspace/src/catkin/third_party/catkin/cmake/toplevel.cmake"\n####\n#### Running command: "cmake /Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/src -DCATKIN_DEVEL_PREFIX=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/devel -DCMAKE_INSTALL_PREFIX=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/install" in "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build"\n####\n####\n#### Running command: "make -j install" in "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Workspaces/FL/team/workspace/build"\n####\n'
p296
sg25
S'project_37850144'
p297
sS'build_success'
p298
I01
sbasb.