(iac.cc.results
Projects
p0
(dp1
S'job_name'
p2
S'test'
p3
sS'projects'
p4
(lp5
(iac.cc.results
Project
p6
(dp7
S'branches'
p8
(dp9
sS'name'
p10
S'CONTINUOUS_INTEGRATION_EXAMPLE'
p11
sS'trace'
p12
S''
p13
sS'testing_error'
p14
g13
sS'catkin_packages'
p15
(lp16
(iac.cc.results
Catkin_package
p17
(dp18
S'doxygen'
p19
Nsg10
S'YAML_CPP'
p20
sS'unit_tests'
p21
(lp22
sS'demos'
p23
(lp24
sS'id'
p25
S'catkin_package_139826881739592'
p26
sS'unit_tests_errors'
p27
Nsba(iac.cc.results
Catkin_package
p28
(dp29
g19
Nsg10
S'ci_example_python'
p30
sg21
(lp31
(iac.cc.results
Unit_tests
p32
(dp33
S'nb_failures'
p34
I0
sS'error'
p35
Nsg10
S'rostest-test_test_pid_ros.xml'
p36
sS'nb_tests'
p37
I1
sS'testsuits'
p38
(dp39
S'unittest.suite.TestSuite'
p40
(iac.cc.results
TestSuit
p41
(dp42
g34
I0
sS'testcases'
p43
(dp44
S'testtest_pid_ros'
p45
(iac.cc.results
TestCase
p46
(dp47
S'failure'
p48
Nsg10
g45
sS'time'
p49
F1.6466
sbssg10
g40
sg37
I1
sbssba(iac.cc.results
Unit_tests
p50
(dp51
g34
I0
sg35
Nsg10
S'nosetests-test.xml'
p52
sg37
I4
sg38
(dp53
S'nosetests'
p54
(iac.cc.results
TestSuit
p55
(dp56
g34
I0
sg43
(dp57
S'test_integral'
p58
(iac.cc.results
TestCase
p59
(dp60
g48
Nsg10
g58
sg49
F0.0
sbsS'test_config_file_factory'
p61
(iac.cc.results
TestCase
p62
(dp63
g48
Nsg10
g61
sg49
F0.002
sbsS'test_default_factory'
p64
(iac.cc.results
TestCase
p65
(dp66
g48
Nsg10
g64
sg49
F0.0
sbsS'test_exception_on_non_existing_config_file'
p67
(iac.cc.results
TestCase
p68
(dp69
g48
Nsg10
g67
sg49
F0.0
sbssg10
g54
sg37
I4
sbssba(iac.cc.results
Unit_tests
p70
(dp71
g34
I0
sg35
Nsg10
S'rosunit-test_pid_ros.xml'
p72
sg37
I1
sg38
(dp73
S'unittest.suite.TestSuite'
p74
(iac.cc.results
TestSuit
p75
(dp76
g34
I0
sg43
(dp77
S'test_ros_param_server_factory'
p78
(iac.cc.results
TestCase
p79
(dp80
g48
Nsg10
g78
sg49
F0.2142
sbssg10
g74
sg37
I1
sbssbasg23
(lp81
(iac.cc.results
Demo
p82
(dp83
g10
S'ci_example_ros_demo'
p84
sS'success'
p85
I01
sS'out'
p86
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/setup.bash\ncd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_python/demos/\nchmod +x ci_example_ros_demo\n./ci_example_ros_demo /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n\n\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n------ setting parameters -----\n\n------ PYTHON DEMO START ------\n\npid using ros parameter server\nreading ros parameters: kp, kd, ki\nPID controller: kp:1 kd:1 ki:1\nforce: -1.101\n\n------ DEMO END ------\n\n... logging to /Network/Servers/bleyl/Volumes/bleyl/vberenz/.ros/log/35e7f9d8-f821-11e5-98c2-b8ca3aad4e6c/roslaunch-bleyl-16814.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is <1GB.\n\x1b]2;roscore\x07\n\x1b[1mstarted roslaunch server http://bleyl:43622/\x1b[0m\nros_comm version 1.9.55\n\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n\nauto-starting new master\n\x1b[1mprocess[master]: started with pid [16829]\x1b[0m\n\x1b[1mROS_MASTER_URI=http://bleyl:11311/\x1b[0m\n\x1b]2;roscore http://bleyl:11311/\x07\n\x1b[1msetting /run_id to 35e7f9d8-f821-11e5-98c2-b8ca3aad4e6c\x1b[0m\n\x1b[1mprocess[rosout-1]: started with pid [16842]\x1b[0m\nstarted core service [/rosout]\n[rosout-1] killing on exit\n[master] killing on exit\nshutting down processing monitor...\n... shutting down processing monitor complete\n\x1b[1mdone\x1b[0m\n'
p87
sba(iac.cc.results
Demo
p88
(dp89
g10
S'ci_example_python_demo'
p90
sg85
I01
sg86
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/setup.bash\ncd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_python/demos/\nchmod +x ci_example_python_demo\n./ci_example_python_demo /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n\n\nbasic pid usage:\nPID controller: kp:1 kd:1 ki:1\nforce: -1.101\npid using default gains:\nPID controller: kp:1 kd:1 ki:1\nforce: -1.101\npid using gains read from config file:\nreading pid gains from:  /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_python/config/test_pid_gains.yaml\nPID controller: kp:1.0 kd:1.0 ki:1.0\nforce: -1.101\n'
p91
sbasg25
S'catkin_package_139826881719328'
p92
sg27
Nsba(iac.cc.results
Catkin_package
p93
(dp94
g19
Nsg10
S'ci_example_cpp'
p95
sg21
(lp96
(iac.cc.results
Unit_tests
p97
(dp98
g34
I0
sg35
Nsg10
S'rosunit-ci_example_rostest.xml'
p99
sg37
I1
sg38
(dp100
S'RosParam_config_test'
p101
(iac.cc.results
TestSuit
p102
(dp103
g34
I0
sg43
(dp104
S'read_parameters_test'
p105
(iac.cc.results
TestCase
p106
(dp107
g48
Nsg10
g105
sg49
F0.403
sbssg10
g101
sg37
I1
sbssba(iac.cc.results
Unit_tests
p108
(dp109
g34
I0
sg35
Nsg10
S'gtest-ci_example_ut.xml'
p110
sg37
I9
sg38
(dp111
S'PID_tests'
p112
(iac.cc.results
TestSuit
p113
(dp114
g34
I0
sg43
(dp115
S'file_configuration_ok_test'
p116
(iac.cc.results
TestCase
p117
(dp118
g48
Nsg10
g116
sg49
F0.001
sbsS'zero_force_at_target'
p119
(iac.cc.results
TestCase
p120
(dp121
g48
Nsg10
g119
sg49
F0.0
sbsS'file_configuration_fail_test'
p122
(iac.cc.results
TestCase
p123
(dp124
g48
Nsg10
g122
sg49
F0.0
sbsS'integral'
p125
(iac.cc.results
TestCase
p126
(dp127
g48
Nsg10
g125
sg49
F0.0
sbsS'right_direction'
p128
(iac.cc.results
TestCase
p129
(dp130
g48
Nsg10
g128
sg49
F0.0
sbsS'default_configuration_test'
p131
(iac.cc.results
TestCase
p132
(dp133
g48
Nsg10
g131
sg49
F0.0
sbsS'read_config_file_test'
p134
(iac.cc.results
TestCase
p135
(dp136
g48
Nsg10
g134
sg49
F0.001
sbsS'configurations_same_results_test'
p137
(iac.cc.results
TestCase
p138
(dp139
g48
Nsg10
g137
sg49
F0.0
sbsS'reset_integral'
p140
(iac.cc.results
TestCase
p141
(dp142
g48
Nsg10
g140
sg49
F0.001
sbssg10
g112
sg37
I9
sbssba(iac.cc.results
Unit_tests
p143
(dp144
g34
I0
sg35
Nsg10
S'rostest-tests_ci_example_rostest.xml'
p145
sg37
I1
sg38
(dp146
S'unittest.suite.TestSuite'
p147
(iac.cc.results
TestSuit
p148
(dp149
g34
I0
sg43
(dp150
S'testci_example_rostest'
p151
(iac.cc.results
TestCase
p152
(dp153
g48
Nsg10
g151
sg49
F1.5458
sbssg10
g147
sg37
I1
sbssbasg23
(lp154
(iac.cc.results
Demo
p155
(dp156
g10
S'ci_example_ros_demo'
p157
sg85
I01
sg86
S"demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/setup.bash\ncd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/\nchmod +x ci_example_ros_demo\n./ci_example_ros_demo /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n\n\n------ setting parameters -----\n\n------ CPP DEMO START ------\n\nThis demo shows how to run a demo that requires complex setup, in this case turning on ROS\nand putting data in ros parameter server.\nThe executable related to this file is not started directly, but via a related executable sh script 'ci_example_ros_demo' \nwhich does all the setup work\nFor equivalent unit-tests implementation, see /tests/ci_example_rostest.cpp\n\ncomputed force: 0.01\n\n------ DEMO END ------\n\n... logging to /Network/Servers/bleyl/Volumes/bleyl/vberenz/.ros/log/3843047a-f821-11e5-b365-b8ca3aad4e6c/roslaunch-bleyl-16967.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is <1GB.\n\x1b]2;roscore\x07\n\x1b[1mstarted roslaunch server http://bleyl:50395/\x1b[0m\nros_comm version 1.9.55\n\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n\nauto-starting new master\n\x1b[1mprocess[master]: started with pid [16982]\x1b[0m\n\x1b[1mROS_MASTER_URI=http://bleyl:11311/\x1b[0m\n\x1b]2;roscore http://bleyl:11311/\x07\n\x1b[1msetting /run_id to 3843047a-f821-11e5-b365-b8ca3aad4e6c\x1b[0m\n\x1b[1mprocess[rosout-1]: started with pid [16995]\x1b[0m\nstarted core service [/rosout]\n[rosout-1] killing on exit\n[master] killing on exit\nshutting down processing monitor...\n... shutting down processing monitor complete\n\x1b[1mdone\x1b[0m\n"
p158
sba(iac.cc.results
Demo
p159
(dp160
g10
S'ci_example_abs_path_config_demo'
p161
sg85
I01
sg86
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/setup.bash\ncd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/ci_example_cpp/\nchmod +x ci_example_abs_path_config_demo\n./ci_example_abs_path_config_demo /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n\n\nThis demo shows how to create an executable run by the continuous integration\nwhich depends on a configuration file. In the solution showed here, the absolute path\nto the configuration file is set during pre-compilation. See code in /demos/ci_example_abs_path_config_demo.cpp\nfor details\n\ngains read from configuration file:\nkp: 1\nkd: 1\nki: 1\ncomputed force: 0.01\n'
p162
sba(iac.cc.results
Demo
p163
(dp164
g10
S'ci_example_demo'
p165
sg85
I01
sg86
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/setup.bash\ncd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/ci_example_cpp/\nchmod +x ci_example_demo\n./ci_example_demo /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n\n\ncomputed force: 0.01\n'
p166
sbasg25
S'catkin_package_139826881686632'
p167
sg27
NsbasS'build_message'
p168
S'COMMAND:catkin_make -j install\n------------------------------\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- The C compiler identification is GNU\n-- The CXX compiler identification is GNU\n-- Check for working C compiler: /usr/bin/gcc\n-- Check for working C compiler: /usr/bin/gcc -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Check for working CXX compiler: /usr/bin/c++\n-- Check for working CXX compiler: /usr/bin/c++ -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Using CATKIN_DEVEL_PREFIX: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n-- Using CMAKE_PREFIX_PATH: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/workspace/devel;/opt/ros/groovy\n-- This workspace overlays: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/workspace/devel;/opt/ros/groovy\n-- Found PythonInterp: /usr/bin/python (found version "2.7.3")\n-- Using PYTHON_EXECUTABLE: /usr/bin/python\n-- Python version: 2.7\n-- Using Debian Python package layout\n-- Using CATKIN_ENABLE_TESTING: ON\n-- Call enable_testing()\n-- Using CATKIN_TEST_RESULTS_DIR: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/test_results\n-- Looking for include files CMAKE_HAVE_PTHREAD_H\n-- Looking for include files CMAKE_HAVE_PTHREAD_H - found\n-- Looking for pthread_create in pthreads\n-- Looking for pthread_create in pthreads - not found\n-- Looking for pthread_create in pthread\n-- Looking for pthread_create in pthread - found\n-- Found Threads: TRUE \n-- Found gtest sources under \'/usr/src/gtest\': gtests will be built\n-- catkin 0.5.89\n-- BUILD_SHARED_LIBS is on\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- ~~  traversing 3 packages in topological order:\n-- ~~  - YAML_CPP\n-- ~~  - ci_example_python\n-- ~~  - ci_example_cpp\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- +++ processing catkin package: \'YAML_CPP\'\n-- ==> add_subdirectory(catkin/third_party/YAML_CPP)\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- Boost version: 1.46.1\n-- Performing Test FLAG_WEXTRA\n-- Performing Test FLAG_WEXTRA - Success\n-- +++ processing catkin package: \'ci_example_python\'\n-- ==> add_subdirectory(catkin/examples/ci_example/ci_example_python)\n-- +++ processing catkin package: \'ci_example_cpp\'\n-- ==> add_subdirectory(catkin/examples/ci_example/ci_example_cpp)\n-- Configuring done\n-- Generating done\n-- Build files have been written to: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build\nScanning dependencies of target yaml-cpp\n[  2%] [  4%] [  6%] [  9%] [ 13%] [ 13%] [ 16%] [ 18%] [ 20%] [ 23%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o\n[ 25%] [ 27%] [ 30%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o\n[ 32%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o\n[ 34%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/regex.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o\n[ 37%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o\n[ 39%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/null.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o\n[ 41%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o\n[ 44%] [ 46%] [ 48%] [ 51%] [ 53%] [ 55%] [ 58%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/node.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o\n[ 60%] [ 62%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o\n[ 65%] [ 67%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o\nLinking CXX shared library /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/libyaml-cpp.so\n[ 67%] Built target yaml-cpp\nScanning dependencies of target read\nScanning dependencies of target parse\nScanning dependencies of target sandbox\nScanning dependencies of target run-tests\nScanning dependencies of target basic_pid\n[ 72%] [ 72%] [ 74%] Building CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/sandbox.dir/sandbox.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/parse.dir/parse.cpp.o\n[ 79%] [ 79%] [ 81%] [ 86%] [ 86%] Building CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/read.dir/read.cpp.o\n[ 88%] [ 90%] Building CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/tests.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/basic_pid.dir/src/basic_pid.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/spectests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/parsertests.cpp.o\n[ 93%] Building CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/emittertests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/nodetests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/main.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/spectests.cpp.o\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/YAML_CPP/parse\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/YAML_CPP/read\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/YAML_CPP/sandbox\n[ 93%] Built target parse\n[ 93%] Built target read\n[ 93%] Built target sandbox\nLinking CXX shared library /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/libbasic_pid.so\n[ 93%] Built target basic_pid\nScanning dependencies of target ci_example_abs_path_config_demo\nScanning dependencies of target ci_example_demo\nScanning dependencies of target ci_example_ros\n[ 95%] [ 97%] [100%] Building CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_ros.dir/src/demos/ci_example_ros.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_abs_path_config_demo.dir/src/demos/ci_example_abs_path_config_demo.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_demo.dir/src/demos/ci_example_demo.cpp.o\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/ci_example_cpp/ci_example_ros\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/ci_example_cpp/ci_example_abs_path_config_demo\n[100%] Built target ci_example_ros\n[100%] Built target ci_example_abs_path_config_demo\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/ci_example_cpp/ci_example_demo\n[100%] Built target ci_example_demo\nLinking CXX executable /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib/YAML_CPP/run-tests\n[100%] Built target run-tests\nInstall the project...\n-- Install configuration: ""\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/_setup_util.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/env.sh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/setup.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/setup.sh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/setup.zsh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/.rosinstall\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/etc/catkin/profile.d/05.catkin_make.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/etc/catkin/profile.d/05.catkin_make_isolated.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/pkgconfig/YAML_CPP.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/share/YAML_CPP/cmake/YAML_CPPConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/share/YAML_CPP/cmake/YAML_CPPConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/share/YAML_CPP/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/libyaml-cpp.so.0.5.1\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/libyaml-cpp.so.0.5\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/libyaml-cpp.so\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/ostream_wrapper.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/noncopyable.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/yaml_eigen.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/null.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/dll.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/mark.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/traits.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/emitter.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/emitterdef.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/emittermanip.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/exceptions.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/eventhandler.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/binary.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/contrib\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/contrib/graphbuilder.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/contrib/anchordict.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/yaml.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/anchor.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/parser.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/stlemitter.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/emitfromevents.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/iterator.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/ptr.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/emit.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/impl.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/convert.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/parse.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/type.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/iterator_fwd.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/iterator.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/bool_type.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/node_data.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/impl.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/memory.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/node_ref.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/node_iterator.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/detail/node.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/include/yaml-cpp/node/node.h\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/pkgconfig/yaml-cpp.pc\n+ [ -n  ]\n+ cd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_python\n+ /usr/bin/env PYTHONPATH=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/lib/python2.7/dist-packages:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/workspace/devel/lib/python2.7/dist-packages:/opt/ros/groovy/lib/python2.7/dist-packages:/opt/ros/groovy/bin:/Network/Servers/bleyl/Volumes/bleyl/vberenz/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/amd-clmc/scripts:/Network/Servers/bleyl/Volumes/bleyl/vberenz/.local/bin:/Network/Servers/bleyl/Volumes/bleyl/vberenz/bin/:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Libraries/aldebaran/pynaoqi-python2.7-2.1.2.17-linux64 CATKIN_BINARY_DIR=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build /usr/bin/python /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_python/setup.py build --build-base /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/catkin/examples/ci_example/ci_example_python install --install-layout=deb --prefix=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install --install-scripts=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/bin\nrunning build\nrunning build_py\npackage init file \'src/__init__.py\' not found (or not a regular file)\npackage init file \'src/__init__.py\' not found (or not a regular file)\nrunning install\nrunning install_lib\nwarning: install_lib: \'/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/catkin/examples/ci_example/ci_example_python/lib.linux-x86_64-2.7\' does not exist -- no Python modules to install\n\nrunning install_egg_info\nCreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages/\nWriting /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages/ci_example_python-1.0.0.egg-info\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/pkgconfig/ci_example_cpp.pc\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/share/ci_example_cpp/cmake/ci_example_cppConfig.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/share/ci_example_cpp/cmake/ci_example_cppConfig-version.cmake\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/share/ci_example_cpp/package.xml\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/bin/ci_example_ros\n-- Set runtime path of "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/bin/ci_example_ros" to "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/lib:/opt/ros/groovy/lib"\nBase path: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace\nSource space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src\nBuild space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build\nDevel space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\nInstall space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install\nCreating symlink "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/CMakeLists.txt" pointing to "/opt/ros/groovy/share/catkin/cmake/toplevel.cmake"\n####\n#### Running command: "cmake /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src -DCATKIN_DEVEL_PREFIX=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel -DCMAKE_INSTALL_PREFIX=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install" in "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build"\n####\n####\n#### Running command: "make -j install" in "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build"\n####\n'
p169
sg25
S'project_139826881589400'
p170
sS'build_success'
p171
I01
sbasb.