(iac.cc.results
Projects
p0
(dp1
S'job_name'
p2
S'test'
p3
sS'projects'
p4
(lp5
(iac.cc.results
Project
p6
(dp7
S'branches'
p8
(dp9
sS'name'
p10
S'PYTHON-FILE-PARSER'
p11
sS'trace'
p12
S''
p13
sS'testing_error'
p14
g13
sS'catkin_packages'
p15
(lp16
(iac.cc.results
Catkin_package
p17
(dp18
S'doxygen'
p19
Nsg10
S'python_file_parser'
p20
sS'unit_tests'
p21
(lp22
(iac.cc.results
Unit_tests
p23
(dp24
S'nb_failures'
p25
I0
sS'error'
p26
Nsg10
S'nosetests-tests.xml'
p27
sS'nb_tests'
p28
I4
sS'testsuits'
p29
(dp30
S'nosetests'
p31
(iac.cc.results
TestSuit
p32
(dp33
g25
I0
sS'testcases'
p34
(dp35
S'test_get_row'
p36
(iac.cc.results
TestCase
p37
(dp38
S'failure'
p39
Nsg10
g36
sS'time'
p40
F0.0
sbsS'test_errors'
p41
(iac.cc.results
TestCase
p42
(dp43
g39
Nsg10
g41
sg40
F0.0
sbsS'test_exceptions'
p44
(iac.cc.results
TestCase
p45
(dp46
g39
Nsg10
g44
sg40
F0.0
sbsS'test_get_column'
p47
(iac.cc.results
TestCase
p48
(dp49
g39
Nsg10
g47
sg40
F0.0
sbssg10
g31
sg28
I4
sbssbasS'demos'
p50
(lp51
(iac.cc.results
Demo
p52
(dp53
g10
S'csv_demo'
p54
sS'success'
p55
I01
sS'out'
p56
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel/setup.bash\ncd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/utilities/python_file_parser/demos/\nchmod +x csv_demo\n./csv_demo /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n\n\n\nnb columns:  65\nnb rows:  2842\nerrors:  0\nfields: \n\tfield.joint_vel8\n\tfield.joint_vel9\n\tfield.joint_pos12\n\tfield.joint_vel2\n\tfield.joint_vel3\n\tfield.joint_vel0\n\tfield.joint_vel1\n\tfield.joint_vel6\n\tfield.joint_pos11\n\tfield.joint_vel4\n\tfield.joint_vel5\n\tfield.joint_pos9\n\tfield.contact7\n\tfield.joint_pos18\n\tfield.joint_pos8\n\tfield.timestep\n\tfield.joint_pos14\n\tfield.joint_vel10\n\tfield.joint_vel11\n\tfield.joint_vel12\n\tfield.joint_vel13\n\tfield.joint_vel14\n\tfield.joint_vel15\n\tfield.joint_vel16\n\tfield.joint_vel17\n\tfield.joint_vel18\n\tfield.joint_vel19\n\tfield.joint_pos19\n\tfield.joint_pos20\n\tfield.joint_pos21\n\tfield.joint_pos13\n\tfield.joint_pos7\n\tfield.contact18\n\tfield.joint_pos10\n\tfield.joint_pos17\n\tfield.joint_pos16\n\tfield.joint_pos15\n\tfield.joint_pos6\n\tfield.contact12\n\tfield.contact13\n\tfield.contact10\n\tfield.contact11\n\tfield.contact16\n\tfield.contact17\n\tfield.contact14\n\tfield.contact15\n\tfield.contact8\n\tfield.contact9\n\tfield.joint_pos5\n\tfield.joint_pos4\n\tfield.joint_pos3\n\tfield.joint_pos2\n\tfield.joint_pos1\n\tfield.joint_pos0\n\tfield.contact0\n\tfield.contact1\n\tfield.contact2\n\tfield.contact3\n\tfield.contact4\n\tfield.contact5\n\tfield.contact6\n\t%time\n\tfield.joint_vel21\n\tfield.joint_vel20\n\tfield.joint_vel7\n\n'
p57
sbasS'id'
p58
S'catkin_package_140691735814440'
p59
sS'unit_tests_errors'
p60
NsbasS'build_message'
p61
S'COMMAND:catkin_make -j install\n------------------------------\n-- The C compiler identification is GNU\n-- The CXX compiler identification is GNU\n-- Check for working C compiler: /usr/bin/gcc\n-- Check for working C compiler: /usr/bin/gcc -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Check for working CXX compiler: /usr/bin/c++\n-- Check for working CXX compiler: /usr/bin/c++ -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Using CATKIN_DEVEL_PREFIX: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\n-- Using CMAKE_PREFIX_PATH: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/workspace/devel;/opt/ros/groovy\n-- This workspace overlays: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/workspace/devel;/opt/ros/groovy\n-- Found PythonInterp: /usr/bin/python (found version "2.7.3")\n-- Using PYTHON_EXECUTABLE: /usr/bin/python\n-- Python version: 2.7\n-- Using Debian Python package layout\n-- Using CATKIN_ENABLE_TESTING: ON\n-- Call enable_testing()\n-- Using CATKIN_TEST_RESULTS_DIR: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/test_results\n-- Looking for include files CMAKE_HAVE_PTHREAD_H\n-- Looking for include files CMAKE_HAVE_PTHREAD_H - found\n-- Looking for pthread_create in pthreads\n-- Looking for pthread_create in pthreads - not found\n-- Looking for pthread_create in pthread\n-- Looking for pthread_create in pthread - found\n-- Found Threads: TRUE \n-- Found gtest sources under \'/usr/src/gtest\': gtests will be built\n-- catkin 0.5.89\n-- BUILD_SHARED_LIBS is on\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- ~~  traversing 1 packages in topological order:\n-- ~~  - python_file_parser\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- +++ processing catkin package: \'python_file_parser\'\n-- ==> add_subdirectory(catkin/utilities/python_file_parser)\n-- Configuring done\n-- Generating done\n-- Build files have been written to: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build\nInstall the project...\n-- Install configuration: ""\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/_setup_util.py\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/env.sh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/setup.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/setup.sh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/setup.zsh\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/.rosinstall\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/etc/catkin/profile.d/05.catkin_make.bash\n-- Installing: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/etc/catkin/profile.d/05.catkin_make_isolated.bash\n+ [ -n  ]\n+ cd /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/utilities/python_file_parser\n+ /usr/bin/env PYTHONPATH=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/lib/python2.7/dist-packages:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/workspace/devel/lib/python2.7/dist-packages:/opt/ros/groovy/lib/python2.7/dist-packages:/opt/ros/groovy/bin:/Network/Servers/bleyl/Volumes/bleyl/vberenz/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/amd-clmc/scripts:/Network/Servers/bleyl/Volumes/bleyl/vberenz/.local/bin:/Network/Servers/bleyl/Volumes/bleyl/vberenz/bin/:/Network/Servers/bleyl/Volumes/bleyl/vberenz/Libraries/aldebaran/pynaoqi-python2.7-2.1.2.17-linux64 CATKIN_BINARY_DIR=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build /usr/bin/python /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/catkin/utilities/python_file_parser/setup.py build --build-base /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/catkin/utilities/python_file_parser install --install-layout=deb --prefix=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install --install-scripts=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/bin\nrunning build\nrunning build_py\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/catkin/utilities/python_file_parser/lib.linux-x86_64-2.7\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/catkin/utilities/python_file_parser/lib.linux-x86_64-2.7/python_file_parser\ncopying src/__init__.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/catkin/utilities/python_file_parser/lib.linux-x86_64-2.7/python_file_parser\nrunning install\nrunning install_lib\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages\ncreating /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages/python_file_parser\ncopying /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build/catkin/utilities/python_file_parser/lib.linux-x86_64-2.7/python_file_parser/__init__.py -> /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages/python_file_parser\nbyte-compiling /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages/python_file_parser/__init__.py to __init__.pyc\nrunning install_egg_info\nWriting /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install/lib/python2.7/dist-packages/python_file_parser-1.0.0.egg-info\nBase path: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace\nSource space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src\nBuild space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build\nDevel space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel\nInstall space: /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install\nCreating symlink "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src/CMakeLists.txt" pointing to "/opt/ros/groovy/share/catkin/cmake/toplevel.cmake"\n####\n#### Running command: "cmake /Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/src -DCATKIN_DEVEL_PREFIX=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/devel -DCMAKE_INSTALL_PREFIX=/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/install" in "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build"\n####\n####\n#### Running command: "make -j install" in "/Network/Servers/bleyl/Volumes/bleyl/vberenz/Software/team/workspace/build"\n####\n'
p62
sg58
S'project_140691735727352'
p63
sS'build_success'
p64
I01
sbasb.