(iac.cc.results
Projects
p0
(dp1
S'job_name'
p2
S'test'
p3
sS'projects'
p4
(lp5
(iac.cc.results
Project
p6
(dp7
S'branches'
p8
(dp9
sS'name'
p10
S'CONTINUOUS_INTEGRATION_EXAMPLE'
p11
sS'trace'
p12
S''
p13
sS'testing_error'
p14
g13
sS'catkin_packages'
p15
(lp16
(iac.cc.results
Catkin_package
p17
(dp18
S'doxygen'
p19
Nsg10
S'YAML_CPP'
p20
sS'unit_tests'
p21
(lp22
sS'demos'
p23
(lp24
sS'id'
p25
S'catkin_package_42038048'
p26
sS'unit_tests_errors'
p27
Nsba(iac.cc.results
Catkin_package
p28
(dp29
g19
Nsg10
S'ci_example_python'
p30
sg21
(lp31
(iac.cc.results
Unit_tests
p32
(dp33
S'nb_failures'
p34
I0
sS'error'
p35
Nsg10
S'rosunit-test_pid_ros.xml'
p36
sS'nb_tests'
p37
I1
sS'testsuits'
p38
(dp39
S'unittest.suite.TestSuite'
p40
(iac.cc.results
TestSuit
p41
(dp42
g34
I0
sS'testcases'
p43
(dp44
S'test_ros_param_server_factory'
p45
(iac.cc.results
TestCase
p46
(dp47
S'failure'
p48
Nsg10
g45
sS'time'
p49
F0.219
sbssg10
g40
sg37
I1
sbssba(iac.cc.results
Unit_tests
p50
(dp51
g34
I0
sg35
Nsg10
S'nosetests-test.xml'
p52
sg37
I4
sg38
(dp53
S'nosetests'
p54
(iac.cc.results
TestSuit
p55
(dp56
g34
I0
sg43
(dp57
S'test_integral'
p58
(iac.cc.results
TestCase
p59
(dp60
g48
Nsg10
g58
sg49
F0.0
sbsS'test_config_file_factory'
p61
(iac.cc.results
TestCase
p62
(dp63
g48
Nsg10
g61
sg49
F0.002
sbsS'test_default_factory'
p64
(iac.cc.results
TestCase
p65
(dp66
g48
Nsg10
g64
sg49
F0.0
sbsS'test_exception_on_non_existing_config_file'
p67
(iac.cc.results
TestCase
p68
(dp69
g48
Nsg10
g67
sg49
F0.0
sbssg10
g54
sg37
I4
sbssba(iac.cc.results
Unit_tests
p70
(dp71
g34
I0
sg35
Nsg10
S'rostest-test_test_pid_ros.xml'
p72
sg37
I1
sg38
(dp73
S'unittest.suite.TestSuite'
p74
(iac.cc.results
TestSuit
p75
(dp76
g34
I0
sg43
(dp77
S'testtest_pid_ros'
p78
(iac.cc.results
TestCase
p79
(dp80
g48
Nsg10
g78
sg49
F2.5396
sbssg10
g74
sg37
I1
sbssbasg23
(lp81
(iac.cc.results
Demo
p82
(dp83
g10
S'ci_example_python_demo'
p84
sS'success'
p85
I00
sS'out'
p86
S'failed to run demo (exception thrown). command: \n\nsource /home/amd_clmc/team/workspace/devel/setup.bash && cd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/demos/ && chmod +x ci_example_python_demo && ./ci_example_python_demo\n\nerror message:\n\n/bin/sh: 1: source: not found\n'
p87
sba(iac.cc.results
Demo
p88
(dp89
g10
S'ci_example_ros_demo'
p90
sg85
I00
sg86
S'failed to run demo (exception thrown). command: \n\nsource /home/amd_clmc/team/workspace/devel/setup.bash && cd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/demos/ && chmod +x ci_example_ros_demo && ./ci_example_ros_demo\n\nerror message:\n\n/bin/sh: 1: source: not found\n'
p91
sbasg25
S'catkin_package_42010096'
p92
sg27
Nsba(iac.cc.results
Catkin_package
p93
(dp94
g19
Nsg10
S'ci_example_cpp'
p95
sg21
(lp96
(iac.cc.results
Unit_tests
p97
(dp98
g34
I0
sg35
Nsg10
S'rosunit-ci_example_rostest.xml'
p99
sg37
I1
sg38
(dp100
S'RosParam_config_test'
p101
(iac.cc.results
TestSuit
p102
(dp103
g34
I0
sg43
(dp104
S'read_parameters_test'
p105
(iac.cc.results
TestCase
p106
(dp107
g48
Nsg10
g105
sg49
F0.304
sbssg10
g101
sg37
I1
sbssba(iac.cc.results
Unit_tests
p108
(dp109
g34
I0
sg35
Nsg10
S'rostest-tests_ci_example_rostest.xml'
p110
sg37
I1
sg38
(dp111
S'unittest.suite.TestSuite'
p112
(iac.cc.results
TestSuit
p113
(dp114
g34
I0
sg43
(dp115
S'testci_example_rostest'
p116
(iac.cc.results
TestCase
p117
(dp118
g48
Nsg10
g116
sg49
F2.1321
sbssg10
g112
sg37
I1
sbssba(iac.cc.results
Unit_tests
p119
(dp120
g34
I0
sg35
Nsg10
S'gtest-ci_example_ut.xml'
p121
sg37
I9
sg38
(dp122
S'PID_tests'
p123
(iac.cc.results
TestSuit
p124
(dp125
g34
I0
sg43
(dp126
S'file_configuration_ok_test'
p127
(iac.cc.results
TestCase
p128
(dp129
g48
Nsg10
g127
sg49
F0.001
sbsS'zero_force_at_target'
p130
(iac.cc.results
TestCase
p131
(dp132
g48
Nsg10
g130
sg49
F0.0
sbsS'file_configuration_fail_test'
p133
(iac.cc.results
TestCase
p134
(dp135
g48
Nsg10
g133
sg49
F0.0
sbsS'integral'
p136
(iac.cc.results
TestCase
p137
(dp138
g48
Nsg10
g136
sg49
F0.0
sbsS'right_direction'
p139
(iac.cc.results
TestCase
p140
(dp141
g48
Nsg10
g139
sg49
F0.0
sbsS'default_configuration_test'
p142
(iac.cc.results
TestCase
p143
(dp144
g48
Nsg10
g142
sg49
F0.001
sbsS'read_config_file_test'
p145
(iac.cc.results
TestCase
p146
(dp147
g48
Nsg10
g145
sg49
F0.001
sbsS'configurations_same_results_test'
p148
(iac.cc.results
TestCase
p149
(dp150
g48
Nsg10
g148
sg49
F0.0
sbsS'reset_integral'
p151
(iac.cc.results
TestCase
p152
(dp153
g48
Nsg10
g151
sg49
F0.001
sbssg10
g123
sg37
I9
sbssbasg23
(lp154
(iac.cc.results
Demo
p155
(dp156
g10
S'ci_example_ros_demo'
p157
sg85
I00
sg86
S'failed to run demo (exception thrown). command: \n\nsource /home/amd_clmc/team/workspace/devel/setup.bash && cd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/ && chmod +x ci_example_ros_demo && ./ci_example_ros_demo\n\nerror message:\n\n/bin/sh: 1: source: not found\n'
p158
sba(iac.cc.results
Demo
p159
(dp160
g10
S'ci_example_demo'
p161
sg85
I00
sg86
S'failed to run demo (exception thrown). command: \n\nsource /home/amd_clmc/team/workspace/devel/setup.bash && cd /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ && chmod +x ci_example_demo && ./ci_example_demo\n\nerror message:\n\n/bin/sh: 1: source: not found\n'
p162
sba(iac.cc.results
Demo
p163
(dp164
g10
S'ci_example_abs_path_config_demo'
p165
sg85
I00
sg86
S'failed to run demo (exception thrown). command: \n\nsource /home/amd_clmc/team/workspace/devel/setup.bash && cd /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ && chmod +x ci_example_abs_path_config_demo && ./ci_example_abs_path_config_demo\n\nerror message:\n\n/bin/sh: 1: source: not found\n'
p166
sbasg25
S'catkin_package_42059608'
p167
sg27
NsbasS'build_message'
p168
S'COMMAND:catkin_make -j install\n------------------------------\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- The C compiler identification is GNU\n-- The CXX compiler identification is GNU\n-- Check for working C compiler: /usr/bin/gcc\n-- Check for working C compiler: /usr/bin/gcc -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Check for working CXX compiler: /usr/bin/c++\n-- Check for working CXX compiler: /usr/bin/c++ -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Using CATKIN_DEVEL_PREFIX: /home/amd_clmc/team/workspace/devel\n-- Using CMAKE_PREFIX_PATH: /opt/ros/groovy\n-- This workspace overlays: /opt/ros/groovy\n-- Found PythonInterp: /usr/bin/python (found version "2.7.3")\n-- Using PYTHON_EXECUTABLE: /usr/bin/python\n-- Python version: 2.7\n-- Using Debian Python package layout\n-- Using CATKIN_ENABLE_TESTING: ON\n-- Call enable_testing()\n-- Using CATKIN_TEST_RESULTS_DIR: /home/amd_clmc/team/workspace/build/test_results\n-- Looking for include files CMAKE_HAVE_PTHREAD_H\n-- Looking for include files CMAKE_HAVE_PTHREAD_H - found\n-- Looking for pthread_create in pthreads\n-- Looking for pthread_create in pthreads - not found\n-- Looking for pthread_create in pthread\n-- Looking for pthread_create in pthread - found\n-- Found Threads: TRUE \n-- Found gtest sources under \'/usr/src/gtest\': gtests will be built\n-- catkin 0.5.89\n-- BUILD_SHARED_LIBS is on\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- ~~  traversing 3 packages in topological order:\n-- ~~  - YAML_CPP\n-- ~~  - ci_example_python\n-- ~~  - ci_example_cpp\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- +++ processing catkin package: \'YAML_CPP\'\n-- ==> add_subdirectory(catkin/third_party/YAML_CPP)\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- Boost version: 1.46.1\n-- Performing Test FLAG_WEXTRA\n-- Performing Test FLAG_WEXTRA - Success\n-- +++ processing catkin package: \'ci_example_python\'\n-- ==> add_subdirectory(catkin/examples/ci_example/ci_example_python)\n-- +++ processing catkin package: \'ci_example_cpp\'\n-- ==> add_subdirectory(catkin/examples/ci_example/ci_example_cpp)\n-- Configuring done\n-- Generating done\n-- Build files have been written to: /home/amd_clmc/team/workspace/build\nScanning dependencies of target yaml-cpp\n[  2%] [  4%] [  6%] [  9%] [ 11%] [ 13%] [ 16%] [ 18%] [ 20%] [ 23%] [ 25%] [ 27%] [ 30%] [ 34%] [ 34%] [ 37%] [ 39%] [ 41%] [ 46%] [ 46%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o\n[ 48%] [ 51%] [ 53%] [ 58%] [ 58%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/node.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o\n[ 60%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o\n[ 65%] [ 65%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o\n[ 67%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/regex.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/null.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o\nLinking CXX shared library /home/amd_clmc/team/workspace/devel/lib/libyaml-cpp.so\n[ 67%] Built target yaml-cpp\nScanning dependencies of target parse\nScanning dependencies of target read\nScanning dependencies of target sandbox\n[ 69%] [ 72%] Scanning dependencies of target run-tests\n[ 74%] Scanning dependencies of target basic_pid\nBuilding CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/parse.dir/parse.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/sandbox.dir/sandbox.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/read.dir/read.cpp.o\n[ 76%] [ 79%] [ 81%] [ 83%] [ 86%] [ 88%] [ 90%] [ 93%] Building CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/main.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/emittertests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/parsertests.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/basic_pid.dir/src/basic_pid.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/tests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/spectests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/nodetests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/spectests.cpp.o\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/sandbox\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/parse\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/read\n[ 93%] [ 93%] Built target parse\nBuilt target sandbox\n[ 93%] Built target read\nLinking CXX shared library /home/amd_clmc/team/workspace/devel/lib/libbasic_pid.so\n[ 93%] Built target basic_pid\nScanning dependencies of target ci_example_abs_path_config_demo\nScanning dependencies of target ci_example_demo\nScanning dependencies of target ci_example_ros\n[100%] [100%] [100%] Building CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_demo.dir/src/demos/ci_example_demo.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_ros.dir/src/demos/ci_example_ros.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_abs_path_config_demo.dir/src/demos/ci_example_abs_path_config_demo.cpp.o\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ci_example_abs_path_config_demo\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ci_example_ros\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ci_example_demo\n[100%] Built target ci_example_abs_path_config_demo\n[100%] [100%] Built target ci_example_demo\nBuilt target ci_example_ros\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/run-tests\n[100%] Built target run-tests\nInstall the project...\n-- Install configuration: ""\n-- Installing: /home/amd_clmc/team/workspace/install/_setup_util.py\n-- Installing: /home/amd_clmc/team/workspace/install/env.sh\n-- Installing: /home/amd_clmc/team/workspace/install/setup.bash\n-- Installing: /home/amd_clmc/team/workspace/install/setup.sh\n-- Installing: /home/amd_clmc/team/workspace/install/setup.zsh\n-- Installing: /home/amd_clmc/team/workspace/install/.rosinstall\n-- Installing: /home/amd_clmc/team/workspace/install/etc/catkin/profile.d/05.catkin_make.bash\n-- Installing: /home/amd_clmc/team/workspace/install/etc/catkin/profile.d/05.catkin_make_isolated.bash\n-- Installing: /home/amd_clmc/team/workspace/install/lib/pkgconfig/YAML_CPP.pc\n-- Installing: /home/amd_clmc/team/workspace/install/share/YAML_CPP/cmake/YAML_CPPConfig.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/YAML_CPP/cmake/YAML_CPPConfig-version.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/YAML_CPP/package.xml\n-- Installing: /home/amd_clmc/team/workspace/install/lib/libyaml-cpp.so.0.5.1\n-- Installing: /home/amd_clmc/team/workspace/install/lib/libyaml-cpp.so.0.5\n-- Installing: /home/amd_clmc/team/workspace/install/lib/libyaml-cpp.so\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/null.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/eventhandler.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/parser.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/ostream_wrapper.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/dll.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/mark.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/convert.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/impl.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/ptr.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/parse.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node_data.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/impl.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/bool_type.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node_iterator.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/memory.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/iterator_fwd.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node_ref.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/iterator.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/emit.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/iterator.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/type.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/node.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/noncopyable.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/yaml.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/binary.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/traits.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/stlemitter.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/exceptions.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emitfromevents.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/contrib\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/contrib/anchordict.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/contrib/graphbuilder.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emitterdef.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/anchor.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emittermanip.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/yaml_eigen.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emitter.h\n-- Installing: /home/amd_clmc/team/workspace/install/lib/pkgconfig/yaml-cpp.pc\n+ [ -n  ]\n+ cd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python\n+ /usr/bin/env PYTHONPATH=/home/amd_clmc/team/workspace/install/lib/python2.7/dist-packages:/home/amd_clmc/team/workspace/build/lib/python2.7/dist-packages:/opt/ros/groovy/lib/python2.7/dist-packages CATKIN_BINARY_DIR=/home/amd_clmc/team/workspace/build /usr/bin/python /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/setup.py build --build-base /home/amd_clmc/team/workspace/build/catkin/examples/ci_example/ci_example_python install --install-layout=deb --prefix=/home/amd_clmc/team/workspace/install --install-scripts=/home/amd_clmc/team/workspace/install/bin\nrunning build\nrunning build_py\npackage init file \'src/__init__.py\' not found (or not a regular file)\npackage init file \'src/__init__.py\' not found (or not a regular file)\nrunning install\nrunning install_lib\nwarning: install_lib: \'/home/amd_clmc/team/workspace/build/catkin/examples/ci_example/ci_example_python/lib.linux-x86_64-2.7\' does not exist -- no Python modules to install\n\nrunning install_egg_info\nCreating /home/amd_clmc/team/workspace/install/lib/python2.7/dist-packages/\nWriting /home/amd_clmc/team/workspace/install/lib/python2.7/dist-packages/ci_example_python-1.0.0.egg-info\n-- Installing: /home/amd_clmc/team/workspace/install/lib/pkgconfig/ci_example_cpp.pc\n-- Installing: /home/amd_clmc/team/workspace/install/share/ci_example_cpp/cmake/ci_example_cppConfig.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/ci_example_cpp/cmake/ci_example_cppConfig-version.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/ci_example_cpp/package.xml\n-- Installing: /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/bin/ci_example_ros\n-- Set runtime path of "/home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/bin/ci_example_ros" to "/home/amd_clmc/team/workspace/install/lib:/home/amd_clmc/team/workspace/devel/lib:/opt/ros/groovy/lib"\nBase path: /home/amd_clmc/team/workspace\nSource space: /home/amd_clmc/team/workspace/src\nBuild space: /home/amd_clmc/team/workspace/build\nDevel space: /home/amd_clmc/team/workspace/devel\nInstall space: /home/amd_clmc/team/workspace/install\nCreating symlink "/home/amd_clmc/team/workspace/src/CMakeLists.txt" pointing to "/opt/ros/groovy/share/catkin/cmake/toplevel.cmake"\n####\n#### Running command: "cmake /home/amd_clmc/team/workspace/src -DCATKIN_DEVEL_PREFIX=/home/amd_clmc/team/workspace/devel -DCMAKE_INSTALL_PREFIX=/home/amd_clmc/team/workspace/install" in "/home/amd_clmc/team/workspace/build"\n####\n####\n#### Running command: "make -j install" in "/home/amd_clmc/team/workspace/build"\n####\n'
p169
sg25
S'project_41564568'
p170
sS'build_success'
p171
I01
sbasb.