(iac.cc.results
Projects
p0
(dp1
S'job_name'
p2
S'test_tutorial'
p3
sS'projects'
p4
(lp5
(iac.cc.results
Project
p6
(dp7
S'branches'
p8
(dp9
S'ci_example'
p10
S'tutorial'
p11
ssS'name'
p12
S'CONTINUOUS_INTEGRATION_EXAMPLE'
p13
sS'trace'
p14
S''
p15
sS'testing_error'
p16
g15
sS'catkin_packages'
p17
(lp18
(iac.cc.results
Catkin_package
p19
(dp20
S'doxygen'
p21
Nsg12
S'YAML_CPP'
p22
sS'unit_tests'
p23
(lp24
sS'demos'
p25
(lp26
sS'id'
p27
S'catkin_package_26410952'
p28
sS'unit_tests_errors'
p29
Nsba(iac.cc.results
Catkin_package
p30
(dp31
g21
Nsg12
S'ci_example_python'
p32
sg23
(lp33
(iac.cc.results
Unit_tests
p34
(dp35
S'nb_failures'
p36
I0
sS'error'
p37
Nsg12
S'rosunit-test_pid_ros.xml'
p38
sS'nb_tests'
p39
I1
sS'testsuits'
p40
(dp41
S'unittest.suite.TestSuite'
p42
(iac.cc.results
TestSuit
p43
(dp44
g36
I0
sS'testcases'
p45
(dp46
S'test_ros_param_server_factory'
p47
(iac.cc.results
TestCase
p48
(dp49
S'failure'
p50
Nsg12
g47
sS'time'
p51
F0.1951
sbssg12
g42
sg39
I1
sbssba(iac.cc.results
Unit_tests
p52
(dp53
g36
I0
sg37
Nsg12
S'nosetests-test.xml'
p54
sg39
I4
sg40
(dp55
S'nosetests'
p56
(iac.cc.results
TestSuit
p57
(dp58
g36
I0
sg45
(dp59
S'test_integral'
p60
(iac.cc.results
TestCase
p61
(dp62
g50
Nsg12
g60
sg51
F0.0
sbsS'test_config_file_factory'
p63
(iac.cc.results
TestCase
p64
(dp65
g50
Nsg12
g63
sg51
F0.002
sbsS'test_default_factory'
p66
(iac.cc.results
TestCase
p67
(dp68
g50
Nsg12
g66
sg51
F0.0
sbsS'test_exception_on_non_existing_config_file'
p69
(iac.cc.results
TestCase
p70
(dp71
g50
Nsg12
g69
sg51
F0.0
sbssg12
g56
sg39
I4
sbssba(iac.cc.results
Unit_tests
p72
(dp73
g36
I0
sg37
Nsg12
S'rostest-test_test_pid_ros.xml'
p74
sg39
I1
sg40
(dp75
S'unittest.suite.TestSuite'
p76
(iac.cc.results
TestSuit
p77
(dp78
g36
I0
sg45
(dp79
S'testtest_pid_ros'
p80
(iac.cc.results
TestCase
p81
(dp82
g50
Nsg12
g80
sg51
F2.6371
sbssg12
g76
sg39
I1
sbssbasg25
(lp83
(iac.cc.results
Demo
p84
(dp85
g12
S'ci_example_python_demo'
p86
sS'success'
p87
I01
sS'out'
p88
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /home/amd_clmc/team/workspace/devel/setup.bash\ncd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/demos/\nchmod +x ci_example_python_demo\n./ci_example_python_demo /home/amd_clmc/team/workspace/devel\n\n\nbasic pid usage:\nPID controller: kp:1 kd:1 ki:1\nforce: -1.101\npid using default gains:\nPID controller: kp:1 kd:1 ki:1\nforce: -1.101\npid using gains read from config file:\nreading pid gains from:  /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/config/test_pid_gains.yaml\nPID controller: kp:1.0 kd:1.0 ki:1.0\nforce: -1.101\n'
p89
sba(iac.cc.results
Demo
p90
(dp91
g12
S'ci_example_ros_demo'
p92
sg87
I01
sg88
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /home/amd_clmc/team/workspace/devel/setup.bash\ncd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/demos/\nchmod +x ci_example_ros_demo\n./ci_example_ros_demo /home/amd_clmc/team/workspace/devel\n\n\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n------ setting parameters -----\n\n------ PYTHON DEMO START ------\n\npid using ros parameter server\nreading ros parameters: kp, kd, ki\nPID controller: kp:1 kd:1 ki:1\nforce: -1.101\n\n------ DEMO END ------\n\n... logging to /root/.ros/log/cbf1f116-0935-11e6-bcf6-0242ac110003/roslaunch-amd_clmc_12_04_ci-1160.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is <1GB.\n\x1b]2;roscore\x07\n\x1b[1mstarted roslaunch server http://amd_clmc_12_04_ci:35119/\x1b[0m\nros_comm version 1.9.55\n\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n\nauto-starting new master\n\x1b[1mprocess[master]: started with pid [1174]\x1b[0m\n\x1b[1mROS_MASTER_URI=http://amd_clmc_12_04_ci:11311/\x1b[0m\n\x1b]2;roscore http://amd_clmc_12_04_ci:11311/\x07\n\x1b[1msetting /run_id to cbf1f116-0935-11e6-bcf6-0242ac110003\x1b[0m\n\x1b[1mprocess[rosout-1]: started with pid [1187]\x1b[0m\nstarted core service [/rosout]\n[rosout-1] killing on exit\n[master] killing on exit\nshutting down processing monitor...\n... shutting down processing monitor complete\n\x1b[1mdone\x1b[0m\n'
p93
sbasg27
S'catkin_package_26422160'
p94
sg29
Nsba(iac.cc.results
Catkin_package
p95
(dp96
g21
Nsg12
S'ci_example_cpp'
p97
sg23
(lp98
(iac.cc.results
Unit_tests
p99
(dp100
g36
I0
sg37
Nsg12
S'rosunit-ci_example_rostest.xml'
p101
sg39
I1
sg40
(dp102
S'RosParam_config_test'
p103
(iac.cc.results
TestSuit
p104
(dp105
g36
I0
sg45
(dp106
S'read_parameters_test'
p107
(iac.cc.results
TestCase
p108
(dp109
g50
Nsg12
g107
sg51
F0.313
sbssg12
g103
sg39
I1
sbssba(iac.cc.results
Unit_tests
p110
(dp111
g36
I0
sg37
Nsg12
S'rostest-tests_ci_example_rostest.xml'
p112
sg39
I1
sg40
(dp113
S'unittest.suite.TestSuite'
p114
(iac.cc.results
TestSuit
p115
(dp116
g36
I0
sg45
(dp117
S'testci_example_rostest'
p118
(iac.cc.results
TestCase
p119
(dp120
g50
Nsg12
g118
sg51
F2.5515
sbssg12
g114
sg39
I1
sbssba(iac.cc.results
Unit_tests
p121
(dp122
g36
I0
sg37
Nsg12
S'gtest-ci_example_ut.xml'
p123
sg39
I9
sg40
(dp124
S'PID_tests'
p125
(iac.cc.results
TestSuit
p126
(dp127
g36
I0
sg45
(dp128
S'file_configuration_ok_test'
p129
(iac.cc.results
TestCase
p130
(dp131
g50
Nsg12
g129
sg51
F0.001
sbsS'zero_force_at_target'
p132
(iac.cc.results
TestCase
p133
(dp134
g50
Nsg12
g132
sg51
F0.0
sbsS'file_configuration_fail_test'
p135
(iac.cc.results
TestCase
p136
(dp137
g50
Nsg12
g135
sg51
F0.001
sbsS'integral'
p138
(iac.cc.results
TestCase
p139
(dp140
g50
Nsg12
g138
sg51
F0.0
sbsS'right_direction'
p141
(iac.cc.results
TestCase
p142
(dp143
g50
Nsg12
g141
sg51
F0.001
sbsS'default_configuration_test'
p144
(iac.cc.results
TestCase
p145
(dp146
g50
Nsg12
g144
sg51
F0.001
sbsS'read_config_file_test'
p147
(iac.cc.results
TestCase
p148
(dp149
g50
Nsg12
g147
sg51
F0.0
sbsS'configurations_same_results_test'
p150
(iac.cc.results
TestCase
p151
(dp152
g50
Nsg12
g150
sg51
F0.001
sbsS'reset_integral'
p153
(iac.cc.results
TestCase
p154
(dp155
g50
Nsg12
g153
sg51
F0.001
sbssg12
g125
sg39
I9
sbssbasg25
(lp156
(iac.cc.results
Demo
p157
(dp158
g12
S'ci_example_ros_demo'
p159
sg87
I01
sg88
S"demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /home/amd_clmc/team/workspace/devel/setup.bash\ncd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/\nchmod +x ci_example_ros_demo\n./ci_example_ros_demo /home/amd_clmc/team/workspace/devel\n\n\n------ setting parameters -----\n\n------ CPP DEMO START ------\n\nThis demo shows how to run a demo that requires complex setup, in this case turning on ROS\nand putting data in ros parameter server.\nThe executable related to this file is not started directly, but via a related executable sh script 'ci_example_ros_demo' \nwhich does all the setup work\nFor equivalent unit-tests implementation, see /tests/ci_example_rostest.cpp\n\ncomputed force: 0.01\n\n------ DEMO END ------\n\n... logging to /root/.ros/log/ce13dd24-0935-11e6-bcf6-0242ac110003/roslaunch-amd_clmc_12_04_ci-1286.log\nChecking log directory for disk usage. This may take awhile.\nPress Ctrl-C to interrupt\nDone checking log file disk usage. Usage is <1GB.\n\x1b]2;roscore\x07\n\x1b[1mstarted roslaunch server http://amd_clmc_12_04_ci:42432/\x1b[0m\nros_comm version 1.9.55\n\n\nSUMMARY\n========\n\nPARAMETERS\n * /rosdistro\n * /rosversion\n\nNODES\n\nauto-starting new master\n\x1b[1mprocess[master]: started with pid [1300]\x1b[0m\n\x1b[1mROS_MASTER_URI=http://amd_clmc_12_04_ci:11311/\x1b[0m\n\x1b]2;roscore http://amd_clmc_12_04_ci:11311/\x07\n\x1b[1msetting /run_id to ce13dd24-0935-11e6-bcf6-0242ac110003\x1b[0m\n\x1b[1mprocess[rosout-1]: started with pid [1313]\x1b[0m\nstarted core service [/rosout]\n[rosout-1] killing on exit\n[master] killing on exit\nshutting down processing monitor...\n... shutting down processing monitor complete\n\x1b[1mdone\x1b[0m\n"
p160
sba(iac.cc.results
Demo
p161
(dp162
g12
S'ci_example_demo'
p163
sg87
I01
sg88
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /home/amd_clmc/team/workspace/devel/setup.bash\ncd /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/\nchmod +x ci_example_demo\n./ci_example_demo /home/amd_clmc/team/workspace/devel\n\n\ncomputed force: 0.01\n'
p164
sba(iac.cc.results
Demo
p165
(dp166
g12
S'ci_example_abs_path_config_demo'
p167
sg87
I01
sg88
S'demo run with success.\n\nlog:\n\n#!/bin/bash\nsource /home/amd_clmc/team/workspace/devel/setup.bash\ncd /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/\nchmod +x ci_example_abs_path_config_demo\n./ci_example_abs_path_config_demo /home/amd_clmc/team/workspace/devel\n\n\nThis demo shows how to create an executable run by the continuous integration\nwhich depends on a configuration file. In the solution showed here, the absolute path\nto the configuration file is set during pre-compilation. See code in /demos/ci_example_abs_path_config_demo.cpp\nfor details\n\ngains read from configuration file:\nkp: 1\nkd: 1\nki: 1\ncomputed force: 0.01\n'
p168
sbasg27
S'catkin_package_24881992'
p169
sg29
NsbasS'build_message'
p170
S'COMMAND:catkin_make -j install\n------------------------------\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- The C compiler identification is GNU\n-- The CXX compiler identification is GNU\n-- Check for working C compiler: /usr/bin/gcc\n-- Check for working C compiler: /usr/bin/gcc -- works\n-- Detecting C compiler ABI info\n-- Detecting C compiler ABI info - done\n-- Check for working CXX compiler: /usr/bin/c++\n-- Check for working CXX compiler: /usr/bin/c++ -- works\n-- Detecting CXX compiler ABI info\n-- Detecting CXX compiler ABI info - done\n-- Using CATKIN_DEVEL_PREFIX: /home/amd_clmc/team/workspace/devel\n-- Using CMAKE_PREFIX_PATH: /opt/ros/groovy\n-- This workspace overlays: /opt/ros/groovy\n-- Found PythonInterp: /usr/bin/python (found version "2.7.3")\n-- Using PYTHON_EXECUTABLE: /usr/bin/python\n-- Python version: 2.7\n-- Using Debian Python package layout\n-- Using CATKIN_ENABLE_TESTING: ON\n-- Call enable_testing()\n-- Using CATKIN_TEST_RESULTS_DIR: /home/amd_clmc/team/workspace/build/test_results\n-- Looking for include files CMAKE_HAVE_PTHREAD_H\n-- Looking for include files CMAKE_HAVE_PTHREAD_H - found\n-- Looking for pthread_create in pthreads\n-- Looking for pthread_create in pthreads - not found\n-- Looking for pthread_create in pthread\n-- Looking for pthread_create in pthread - found\n-- Found Threads: TRUE \n-- Found gtest sources under \'/usr/src/gtest\': gtests will be built\n-- catkin 0.5.89\n-- BUILD_SHARED_LIBS is on\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- ~~  traversing 3 packages in topological order:\n-- ~~  - YAML_CPP\n-- ~~  - ci_example_python\n-- ~~  - ci_example_cpp\n-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n-- +++ processing catkin package: \'YAML_CPP\'\n-- ==> add_subdirectory(catkin/third_party/YAML_CPP)\nWARNING: Package name "YAML_CPP" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits and underscores.\n-- Boost version: 1.46.1\n-- Performing Test FLAG_WEXTRA\n-- Performing Test FLAG_WEXTRA - Success\n-- +++ processing catkin package: \'ci_example_python\'\n-- ==> add_subdirectory(catkin/examples/ci_example/ci_example_python)\n-- +++ processing catkin package: \'ci_example_cpp\'\n-- ==> add_subdirectory(catkin/examples/ci_example/ci_example_cpp)\n-- Configuring done\n-- Generating done\n-- Build files have been written to: /home/amd_clmc/team/workspace/build\nScanning dependencies of target yaml-cpp\n[  2%] [  4%] [  6%] [  9%] [ 11%] [ 13%] [ 16%] [ 18%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o\n[ 20%] [ 23%] [ 25%] [ 27%] [ 32%] [ 32%] [ 34%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o\n[ 39%] [ 39%] [ 41%] [ 44%] [ 48%] [ 48%] [ 51%] [ 53%] [ 55%] [ 58%] [ 62%] [ 62%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/node.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o\n[ 65%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o\n[ 67%] Building CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/regex.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/null.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o\nLinking CXX shared library /home/amd_clmc/team/workspace/devel/lib/libyaml-cpp.so\n[ 67%] Built target yaml-cpp\nScanning dependencies of target read\nScanning dependencies of target sandbox\nScanning dependencies of target parse\n[ 72%] [ 72%] [ 74%] Building CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/read.dir/read.cpp.o\nScanning dependencies of target run-tests\nBuilding CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/parse.dir/parse.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/util/CMakeFiles/sandbox.dir/sandbox.cpp.o\nScanning dependencies of target basic_pid\n[ 76%] [ 79%] [ 83%] [ 83%] [ 86%] [ 88%] [ 90%] [ 93%] Building CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/spectests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/nodetests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/spectests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/new-api/parsertests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/main.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/tests.cpp.o\nBuilding CXX object catkin/third_party/YAML_CPP/test/CMakeFiles/run-tests.dir/emittertests.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/basic_pid.dir/src/basic_pid.cpp.o\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/read\n[ 93%] Built target read\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/sandbox\n[ 93%] Built target sandbox\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/parse\n[ 93%] Built target parse\nLinking CXX shared library /home/amd_clmc/team/workspace/devel/lib/libbasic_pid.so\n[ 93%] Built target basic_pid\nScanning dependencies of target ci_example_abs_path_config_demo\nScanning dependencies of target ci_example_demo\nScanning dependencies of target ci_example_ros\n[ 97%] [100%] [100%] Building CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_demo.dir/src/demos/ci_example_demo.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_abs_path_config_demo.dir/src/demos/ci_example_abs_path_config_demo.cpp.o\nBuilding CXX object catkin/examples/ci_example/ci_example_cpp/CMakeFiles/ci_example_ros.dir/src/demos/ci_example_ros.cpp.o\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ci_example_abs_path_config_demo\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ci_example_demo\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/ci_example_cpp/ci_example_ros\n[100%] Built target ci_example_abs_path_config_demo\n[100%] Built target ci_example_demo\n[100%] Built target ci_example_ros\nLinking CXX executable /home/amd_clmc/team/workspace/devel/lib/YAML_CPP/run-tests\n[100%] Built target run-tests\nInstall the project...\n-- Install configuration: ""\n-- Installing: /home/amd_clmc/team/workspace/install/_setup_util.py\n-- Installing: /home/amd_clmc/team/workspace/install/env.sh\n-- Installing: /home/amd_clmc/team/workspace/install/setup.bash\n-- Installing: /home/amd_clmc/team/workspace/install/setup.sh\n-- Installing: /home/amd_clmc/team/workspace/install/setup.zsh\n-- Installing: /home/amd_clmc/team/workspace/install/.rosinstall\n-- Installing: /home/amd_clmc/team/workspace/install/etc/catkin/profile.d/05.catkin_make.bash\n-- Installing: /home/amd_clmc/team/workspace/install/etc/catkin/profile.d/05.catkin_make_isolated.bash\n-- Installing: /home/amd_clmc/team/workspace/install/lib/pkgconfig/YAML_CPP.pc\n-- Installing: /home/amd_clmc/team/workspace/install/share/YAML_CPP/cmake/YAML_CPPConfig.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/YAML_CPP/cmake/YAML_CPPConfig-version.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/YAML_CPP/package.xml\n-- Installing: /home/amd_clmc/team/workspace/install/lib/libyaml-cpp.so.0.5.1\n-- Installing: /home/amd_clmc/team/workspace/install/lib/libyaml-cpp.so.0.5\n-- Installing: /home/amd_clmc/team/workspace/install/lib/libyaml-cpp.so\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/null.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/eventhandler.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/parser.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/ostream_wrapper.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/dll.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/mark.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/convert.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/impl.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/ptr.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/parse.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node_data.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/impl.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/bool_type.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node_iterator.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/memory.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/iterator_fwd.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node_ref.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/iterator.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/detail/node.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/emit.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/iterator.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/type.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/node/node.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/noncopyable.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/yaml.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/binary.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/traits.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/stlemitter.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/exceptions.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emitfromevents.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/contrib\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/contrib/anchordict.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/contrib/graphbuilder.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emitterdef.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/anchor.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emittermanip.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/yaml_eigen.h\n-- Installing: /home/amd_clmc/team/workspace/install/include/yaml-cpp/emitter.h\n-- Installing: /home/amd_clmc/team/workspace/install/lib/pkgconfig/yaml-cpp.pc\n+ [ -n  ]\n+ cd /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python\n+ /usr/bin/env PYTHONPATH=/home/amd_clmc/team/workspace/install/lib/python2.7/dist-packages:/home/amd_clmc/team/workspace/build/lib/python2.7/dist-packages:/opt/ros/groovy/lib/python2.7/dist-packages CATKIN_BINARY_DIR=/home/amd_clmc/team/workspace/build /usr/bin/python /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_python/setup.py build --build-base /home/amd_clmc/team/workspace/build/catkin/examples/ci_example/ci_example_python install --install-layout=deb --prefix=/home/amd_clmc/team/workspace/install --install-scripts=/home/amd_clmc/team/workspace/install/bin\npackage init file \'src/__init__.py\' not found (or not a regular file)\npackage init file \'src/__init__.py\' not found (or not a regular file)\nrunning build\nrunning build_py\nrunning install\nwarning: install_lib: \'/home/amd_clmc/team/workspace/build/catkin/examples/ci_example/ci_example_python/lib.linux-x86_64-2.7\' does not exist -- no Python modules to install\n\nrunning install_lib\nrunning install_egg_info\nCreating /home/amd_clmc/team/workspace/install/lib/python2.7/dist-packages/\nWriting /home/amd_clmc/team/workspace/install/lib/python2.7/dist-packages/ci_example_python-1.0.0.egg-info\n-- Installing: /home/amd_clmc/team/workspace/install/lib/pkgconfig/ci_example_cpp.pc\n-- Installing: /home/amd_clmc/team/workspace/install/share/ci_example_cpp/cmake/ci_example_cppConfig.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/ci_example_cpp/cmake/ci_example_cppConfig-version.cmake\n-- Installing: /home/amd_clmc/team/workspace/install/share/ci_example_cpp/package.xml\n-- Installing: /home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/bin/ci_example_ros\n-- Set runtime path of "/home/amd_clmc/team/workspace/src/catkin/examples/ci_example/ci_example_cpp/demos/bin/ci_example_ros" to "/home/amd_clmc/team/workspace/install/lib:/home/amd_clmc/team/workspace/devel/lib:/opt/ros/groovy/lib"\nBase path: /home/amd_clmc/team/workspace\nSource space: /home/amd_clmc/team/workspace/src\nBuild space: /home/amd_clmc/team/workspace/build\nDevel space: /home/amd_clmc/team/workspace/devel\nInstall space: /home/amd_clmc/team/workspace/install\nCreating symlink "/home/amd_clmc/team/workspace/src/CMakeLists.txt" pointing to "/opt/ros/groovy/share/catkin/cmake/toplevel.cmake"\n####\n#### Running command: "cmake /home/amd_clmc/team/workspace/src -DCATKIN_DEVEL_PREFIX=/home/amd_clmc/team/workspace/devel -DCMAKE_INSTALL_PREFIX=/home/amd_clmc/team/workspace/install" in "/home/amd_clmc/team/workspace/build"\n####\n####\n#### Running command: "make -j install" in "/home/amd_clmc/team/workspace/build"\n####\n'
p171
sg27
S'project_24743304'
p172
sS'build_success'
p173
I01
sbasb.